{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for Syntax.
--   Generated by the BNF converter.

module Syntax.Print where

import qualified Syntax.Abs
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Syntax.Abs.Ident where
  prt _ (Syntax.Abs.Ident i) = doc (showString i)

instance Print Syntax.Abs.Neg where
  prt _ (Syntax.Abs.Neg i) = doc (showString i)

instance Print Syntax.Abs.And where
  prt _ (Syntax.Abs.And i) = doc (showString i)

instance Print Syntax.Abs.Or where
  prt _ (Syntax.Abs.Or i) = doc (showString i)

instance Print Syntax.Abs.AExp where
  prt i e = case e of
    Syntax.Abs.EInt n -> prPrec i 2 (concatD [prt 0 n])
    Syntax.Abs.EVar id -> prPrec i 2 (concatD [prt 0 id])
    Syntax.Abs.ETimes aexp1 aexp2 -> prPrec i 1 (concatD [prt 1 aexp1, doc (showString "*"), prt 2 aexp2])
    Syntax.Abs.EPlus aexp1 aexp2 -> prPrec i 0 (concatD [prt 0 aexp1, doc (showString "+"), prt 1 aexp2])
    Syntax.Abs.ESub aexp1 aexp2 -> prPrec i 0 (concatD [prt 0 aexp1, doc (showString "-"), prt 1 aexp2])

instance Print Syntax.Abs.BVal where
  prt i e = case e of
    Syntax.Abs.BTrue -> prPrec i 0 (concatD [doc (showString "true")])
    Syntax.Abs.BFalse -> prPrec i 0 (concatD [doc (showString "false")])

instance Print Syntax.Abs.BExp where
  prt i e = case e of
    Syntax.Abs.EVal bval -> prPrec i 3 (concatD [prt 0 bval])
    Syntax.Abs.EEq aexp1 aexp2 -> prPrec i 3 (concatD [prt 0 aexp1, doc (showString "=="), prt 0 aexp2])
    Syntax.Abs.ELeq aexp1 aexp2 -> prPrec i 3 (concatD [prt 0 aexp1, doc (showString "<="), prt 0 aexp2])
    Syntax.Abs.ENeg neg bexp -> prPrec i 2 (concatD [prt 0 neg, prt 3 bexp])
    Syntax.Abs.EAnd bexp1 and bexp2 -> prPrec i 1 (concatD [prt 1 bexp1, prt 0 and, prt 2 bexp2])
    Syntax.Abs.AOr bexp1 or bexp2 -> prPrec i 0 (concatD [prt 0 bexp1, prt 0 or, prt 1 bexp2])

instance Print Syntax.Abs.Com where
  prt i e = case e of
    Syntax.Abs.CSkip -> prPrec i 2 (concatD [doc (showString "skip")])
    Syntax.Abs.CAssign id aexp -> prPrec i 2 (concatD [prt 0 id, doc (showString ":="), prt 0 aexp])
    Syntax.Abs.CSeq com1 com2 -> prPrec i 1 (concatD [prt 2 com1, doc (showString ";"), prt 1 com2])
    Syntax.Abs.CIte bexp com1 com2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 bexp, doc (showString "then"), prt 1 com1, doc (showString "else"), prt 0 com2])
    Syntax.Abs.CWhile bexp com -> prPrec i 0 (concatD [doc (showString "while"), prt 0 bexp, doc (showString "do"), prt 0 com])

instance Print Syntax.Abs.Assign where
  prt i e = case e of
    Syntax.Abs.Assign id n -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 n])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Syntax.Abs.Assign] where
  prt = prtList

instance Print Syntax.Abs.Env where
  prt i e = case e of
    Syntax.Abs.Env assigns -> prPrec i 0 (concatD [prt 0 assigns])

